name: EvalAI Starter CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install requests pyyaml PyGithub

    - name: Validate challenge configuration using EvalAI API
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
        HOST_AUTH_TOKEN: ${{ secrets.EVALAI_AUTH_TOKEN }}
        CHALLENGE_HOST_TEAM_PK: ${{ secrets.CHALLENGE_HOST_TEAM_PK }}
        EVALAI_HOST_URL: ${{ secrets.EVALAI_HOST_URL }}
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        python github/challenge_processing_script.py
