name: EvalAI Starter CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pip install requests pyyaml PyGithub

    - name: Validate challenge configuration using EvalAI API
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        HOST_AUTH_TOKEN: ${{ secrets.EVALAI_AUTH_TOKEN }}
        CHALLENGE_HOST_TEAM_PK: ${{ secrets.CHALLENGE_HOST_TEAM_PK }}
        EVALAI_HOST_URL: ${{ secrets.EVALAI_HOST_URL }}
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "EVALAI_HOST_URL: ${EVALAI_HOST_URL}"
        echo "CHALLENGE_HOST_TEAM_PK: ${CHALLENGE_HOST_TEAM_PK}"
        echo "GITHUB_CONTEXT: ${GITHUB_CONTEXT}"
        echo "GITHUB_AUTH_TOKEN: ${AUTH_TOKEN}"
        echo "HOST_AUTH_TOKEN: ${EVALAI_AUTH_TOKEN}"
        python github/challenge_processing_script.py
