name: Challenge Config Validation

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Validate challenge config
        env:
          EVALAI_AUTH_TOKEN: ${{ secrets.EVALAI_AUTH_TOKEN }}
          CHALLENGE_HOST_TEAM_PK: ${{ secrets.CHALLENGE_HOST_TEAM_PK }}
          GITHUB_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          python github/validate_challenge_config.py