name: EvalAI Starter CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pyyaml jsonschema

    - name: Validate challenge configuration
      run: python validate_config.py
