name: Validate Host Config

on:
  push:
    branches:
      - challenge

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  validate-host-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate host_config.json
        id: validate
        run: |
          if ! [ -f "github/host_config.json" ]; then
            echo "host_config.json not found in github/ directory"
            echo "invalid=true" >> $GITHUB_OUTPUT
            exit 1
          fi

          TOKEN=$(jq -r '.token' github/host_config.json)
          TEAM_PK=$(jq -r '.team_pk' github/host_config.json)
          HOST_URL=$(jq -r '.evalai_host_url' github/host_config.json)

          if [[ -z "$TOKEN" || "$TOKEN" == "<evalai_user_auth_token>" ]]; then
            echo "Invalid or missing token"
            echo "invalid=true" >> $GITHUB_OUTPUT
            exit 1
          fi

          if [[ -z "$TEAM_PK" || "$TEAM_PK" == "<host_team_pk>" ]]; then
            echo "Invalid or missing team_pk"
            echo "invalid=true" >> $GITHUB_OUTPUT
            exit 1
          fi

          if [[ -z "$HOST_URL" || "$HOST_URL" == "<evalai_host_url>" ]]; then
            echo "Invalid or missing evalai_host_url"
            echo "invalid=true" >> $GITHUB_OUTPUT
            exit 1
          fi

          echo "All values are valid"
          echo "invalid=false" >> $GITHUB_OUTPUT

      - name: Create issue if invalid
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "host_config.json needs real credentials"
          content-filepath: .github/issue_templates/invalid_host_config.md
          labels: |
            bug
            config
